In [2]:
import numpy as np

In [4]:
input_first_series = np.array([3])
weight = np.array([5])
output = input_first_series.dot(weight)

print(f"Input (first series):\n{input_first_series}\n")
print(f"Weights:\n{weight}\n")
print(f"Output:\n{output}\n")

Input (first series):
[3]

Weights:
[15]

Output:
45



---
# NN with Multiple-Input and Single-Output

In [14]:
input_first_series = np.array([3, 5, 7])
weight = np.array([[1], 
                   [2], 
                   [3]])
# output = input_first_series.dot(weight)
output = input_first_series * weight

print(f"Input (first series):\n{input_first_series}\n")
print(f"Weights:\n{weight}\n")
print(f"Output:\n{output}\n")

Input (first series):
[3 5 7]

Weights:
[[1]
 [2]
 [3]]

Output:
[[ 3  5  7]
 [ 6 10 14]
 [ 9 15 21]]

